### ISSUE TITLE
Link to Herbal Plants on the footer of the page returns a blank page

### ISSUE THREAD

**Issue by saurabhshukla689** [kishoranushka/HerbalSphere#16]
Link to Herbal Plants on the footer of the page returns a blank page

Hi @imabhinavdev , @kishoranushka , @abhiMewada97 .
Could one of you please give me write access to this repo so I can start contributing.
I just wanted to assign this issue to myself.

**Comment by imabhinavdev** [comment]
Happy to see that you want to contribute, but this is not an open source project. This is our university project.
